name: Build Site

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup package manager
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Run Static Site Generator
        run: pnpm build

      - name: Apply Changes
        run: |
          git remote update
          git fetch
          git checkout origin/build
          cp public/* . -r

      - name: Commit Changes
        run: |
          git add .
          git config --local user.email "hayih87429@dxecig.com"
          git config --local user.name "pmh-auto"
          git commit -am "build: $(git log --format="%H" -n 1)"

      - name: Push Commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
